
all: pweb_home_agent_test

pweb_home_agent_test:		cassandra_db.o pweb_home_agent_test.o home_agent_index_cassandra_controller.o home_agent_index.o device_cassandra_controller.o device.o user_cassandra_controller.o user.o udp_connection.o io_service_pool.o dns_message_handler.o dns_message.o 
				g++ -Wall -g obj/cassandra_db.o obj/pweb_home_agent_test.o obj/home_agent_index_cassandra_controller.o obj/home_agent_index.o obj/device_cassandra_controller.o obj/device.o obj/user_cassandra_controller.o obj/user.o obj/udp_connection.o obj/io_service_pool.o obj/dns_message_handler.o obj/dns_message.o -lpthread -lboost_system -lboost_thread -lssl -lcrypto -lcql -o bin/pweb_home_agent_test

home_agent_index_cassandra_controller.o: src/controllers/home_agent_index_cassandra_controller.cpp
				g++ -Wall -c -g src/controllers/home_agent_index_cassandra_controller.cpp -o obj/home_agent_index_cassandra_controller.o

home_agent_index.o:		src/models/home_agent_index.cpp
				g++ -Wall -c -g src/models/home_agent_index.cpp -o obj/home_agent_index.o

device_cassandra_controller.o: src/controllers/device_cassandra_controller.cpp
				g++ -Wall -c -g src/controllers/device_cassandra_controller.cpp -o obj/device_cassandra_controller.o

device.o: 			src/models/device.cpp
				g++ -Wall -c -g src/models/device.cpp -o obj/device.o

user_cassandra_controller.o:	src/controllers/user_cassandra_controller.cpp
				g++ -Wall -c -g src/controllers/user_cassandra_controller.cpp -o obj/user_cassandra_controller.o

user.o: 			src/models/user.cpp
				g++ -Wall -c -g src/models/user.cpp -o obj/user.o

cassandra_db.o:			src/database/cassandra_db.cpp
				g++ -Wall -c -g src/database/cassandra_db.cpp -o obj/cassandra_db.o

io_service_pool.o:		src/communication/io_service_pool.cpp
				g++ -Wall -c -g src/communication/io_service_pool.cpp -o obj/io_service_pool.o

udp_connection.o:		src/server/home_agent_server/udp_connection.cpp
				g++ -Wall -c -g src/server/home_agent_server/udp_connection.cpp -o obj/udp_connection.o

dns_message_handler.o:		src/protocol/dns/dns_message_handler.cpp
				g++ -Wall -c -g src/protocol/dns/dns_message_handler.cpp -o obj/dns_message_handler.o

dns_message.o:			src/protocol/dns/datastructure/dns_message.cpp
				g++ -Wall -c -g src/protocol/dns/datastructure/dns_message.cpp -o obj/dns_message.o				

pweb_home_agent_test.o:		src/test/pweb_home_agent_test.cpp
				g++ -Wall -c -g src/test/pweb_home_agent_test.cpp -o obj/pweb_home_agent_test.o

clean:
			rm -rf obj/*
			rm -rf bin/*


