#!/bin/bash
# add to crontab * * * * *    /home/ubuntu/pweb_home_agent/restart-ha

if pgrep pweb_home_agent >/dev/null 2>&1
  then
     echo ':)'
  else
     echo ':('
     /home/ubuntu/pweb_home_agent/bin/pweb_home_agent -a mg -t 4 -P 8080 -d "McGill Home Agent" &> /home/ubuntu/ha-logs/log &
#     /home/ubuntu/pweb_home_agent/bin/pweb_home_agent -a mg -t 4 -P 8080 -d "Carlton Home Agent" &> /home/ubuntu/ha-logs/log &
fi
